name: rt

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip>=24.2
  - numpy>=1.26,<2.1
  - scipy>=1.13
  - scikit-learn>=1.5,<1.6
  - matplotlib>=3.9
  - tqdm>=4.66
  - rust>=1.82
  - uv>=0.5

  - pip:
    - --extra-index-url https://pypi.nvidia.com
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch>=2.7.0
    - torchvision
    - torchaudio
    - einops>=0.8.0
    - ml-dtypes>=0.4.0
    - sentence-transformers>=3.3.0
    - transformers>=4.46.0
    - strictfire>=0.1.0
    - orjson>=3.10.0
    - maturin[patchelf]>=1.7.0
    - maturin-import-hook>=0.1.0
    - relbench>=1.1.0
    - wandb>=0.18.0
    - polars>=1.15.0
    - hatchling>=1.25.0